//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySportBets.UserInterface.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IUserValidator")]
    public interface IUserValidator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserValidator/CheckRegUser", ReplyAction="http://tempuri.org/IUserValidator/CheckRegUserResponse")]
        MySportBets.Model.Model.User[] CheckRegUser(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserValidator/CheckRegUser", ReplyAction="http://tempuri.org/IUserValidator/CheckRegUserResponse")]
        System.Threading.Tasks.Task<MySportBets.Model.Model.User[]> CheckRegUserAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserValidator/RegistrationNewUser", ReplyAction="http://tempuri.org/IUserValidator/RegistrationNewUserResponse")]
        int RegistrationNewUser(MySportBets.Model.Model.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserValidator/RegistrationNewUser", ReplyAction="http://tempuri.org/IUserValidator/RegistrationNewUserResponse")]
        System.Threading.Tasks.Task<int> RegistrationNewUserAsync(MySportBets.Model.Model.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserValidatorChannel : MySportBets.UserInterface.ServiceReference1.IUserValidator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserValidatorClient : System.ServiceModel.ClientBase<MySportBets.UserInterface.ServiceReference1.IUserValidator>, MySportBets.UserInterface.ServiceReference1.IUserValidator {
        
        public UserValidatorClient() {
        }
        
        public UserValidatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserValidatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserValidatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserValidatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MySportBets.Model.Model.User[] CheckRegUser(string login, string password) {
            return base.Channel.CheckRegUser(login, password);
        }
        
        public System.Threading.Tasks.Task<MySportBets.Model.Model.User[]> CheckRegUserAsync(string login, string password) {
            return base.Channel.CheckRegUserAsync(login, password);
        }
        
        public int RegistrationNewUser(MySportBets.Model.Model.User user) {
            return base.Channel.RegistrationNewUser(user);
        }
        
        public System.Threading.Tasks.Task<int> RegistrationNewUserAsync(MySportBets.Model.Model.User user) {
            return base.Channel.RegistrationNewUserAsync(user);
        }
    }
}
